# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Central Ohio .Net Developers Group
email: contact@condg.org
description: Expertise. Community. Involvement.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://condg.org" # the base hostname & protocol for your site
twitter_username: condg
github_username:  condg
facebook_username: condg

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
