# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname
url: "http://condg.org"
baseurl: ""

# Name of website
title: Central Ohio .Net Developers Group

# Short description of your site
description: Expertise. Community. Involvement.

# Github Repository
repository: condg/condg.github.io

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About: "about"
  Schedule: "schedule"
  Events: "events"
  Sponsors: "sponsors"
  
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: ""

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: ""

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Central Ohio .Net Developers Group
  email: "condgorg@outlook.com"
  facebook: condg
  github: condg
  twitter: condg

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: false
  twitter: true
  github: true
  linkedin: false
  snapchat: false
  instagram: false
  youtube: false
  telephone: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "CONDG.Org"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

gems:
  - jekyll-feed
  - jekyll-redirect-from
  
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
